### ISSUE TITLE
Problems implementing zip file package support for Windows

### ISSUE THREAD

**Issue by MarkusPiotrowski** [beeware/briefcase#1176]
### What is the problem or limitation you are having?

I like to implement a `-p zip` option for the package command for Windows. I did this successfully on my local briefcase installation (0.3.12).

Now I want to do the same on the recent dev branch. However, when running `tox` I got KeyErrors about 'packaging_format' from ` tests/platforms/windows/app/test_package.py`. 

This is what I changed in principle in `briefcase\src\briefcase\platforms\windows\__init__.py`: 

```python
...
import shutil
...

class WindowsPackageCommand(PackageCommand):
    @property
    def packaging_formats(self):
        return ["msi", "zip"]
...

def package_app(
       ...
    ):
        """Package an application.

        ...
        """

        # Easy package first: Just pack the 'binary' folder as zip:
        if kwargs['packaging_format'] == "zip":
            self.logger.info("Building zip file...", prefix=app.app_name)
            shutil.make_archive(
                self.distribution_path(app)[:-3],  # rem.'msi', shutil adds zip 
                "zip",
                self.bundle_path(app) / self.packaging_root,
            )
            return
        ...
```
As said, these changes work in 0.3.12, but already in 0.3.13 I got a KeyError: 'packaging_format' for the line `if kwargs['packaging_format'] == 'zip'`' 

So the `-p` parameter seems to be no longer passed on. Can you give me hint, where it is lost?

### Describe the solution you'd like

The value of the `package -p` parameter should be passed to the `WindowsPackageCommand` class to allow for alternative packing (e.g. as zip).

### Describe alternatives you've considered

None so far. It was said before (e.g. issue #457 and recent discord discussion) that a `package -p zip` option is easy to implement and would be considered for merging.

**Comment by rmartin16** [comment]
PR #1107 moved `packaging_format` to the `app`. So, you can access it via `app.packaging_format` in the windows package command. You can see this in `src/briefcase/platforms/macOS/__init__.py` as an example.

**Comment by MarkusPiotrowski** [comment]
As said, `app.packaging_format` does no longer work in the dev branch: `AttributeError: 'AppConfig' object has no attribute 'packaging_format'`.
 The `app` parameter is now of type `AppConfig` and not longer `BaseConfig`. Where does 'packaging_format' went lost?

**Comment by rmartin16** [comment]
`app.packaging_format` is being [set in the Package Command](https://github.com/beeware/briefcase/blob/52e7f05185d769466ca2db1e220f679f7c80a6a4/src/briefcase/commands/package.py#L82). So, if the test doesn't run through that code, `packaging_format` won't exist on `app`; it may need to be set on the test app manually as several tests currently do. I'm happy to take a look at a specific example if you have code published somewhere.
